[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[lib]
name = "util"
path = "src/util.rs"

[dependencies]
itertools = "0.13"
regex = "1.11"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_panics_doc = "allow"

[profile.release]
overflow-checks = true
