[package]
name = "advent_of_code_2021"
version = "0.1.0"
edition = "2021"

[lib]
name = "util"
path = "src/util.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
